### ISSUE TITLE
etcd client: compile error

### ISSUE THREAD

**Issue by foxmailed** [coreos/etcd#5097]
1.github.com/coreos/etcd/client/keys.generated.go:83: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
2. github.com/coreos/etcd/client/cancelreq.go:13: req.Cancel undefined (type *http.Request has no field or method Cancel)
3. github.com/coreos/etcd/pkg/httputil/httputil.go:18: req.Cancel undefined (type *http.Request has no field or method Cancel)
4. /home/wudi/code/src/github.com/coreos/etcd/auth/store.go:202: undefined: strings.Compare

golang version: 1.4.2

**Comment by xiang90** [comment]
go 1.4 is not supported anymore. try go 1.5+. or you can try to build with 2.3 release branch.
