### ISSUE TITLE
Master not building

### ISSUE THREAD

**Issue by braddeicide** [coreos/etcd#7849]
Currently unable to build skydns due to the "transport" errors, can replicate by trying to build etcd master using official steps.

```bash
# git clone https://github.com/coreos/etcd.git
Cloning into 'etcd'...
remote: Counting objects: 61749, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 61749 (delta 12), reused 0 (delta 0), pack-reused 61711
Receiving objects: 100% (61749/61749), 30.13 MiB | 206.00 KiB/s, done.
Resolving deltas: 100% (38453/38453), done.
~ # cd etcd/
~/etcd # ./build
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener.go:180: undefined: tls.CertificateRequestInfo
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:151: undefined: net.DefaultResolver in net.DefaultResolver.LookupHost
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/netutil.go:45: undefined: net.DefaultResolver in net.DefaultResolver.LookupPort
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/netutil.go:55: undefined: net.DefaultResolver in net.DefaultResolver.LookupIPAddr
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/debugutil
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/debugutil/pprof.go:28: undefined: runtime.SetMutexProfileFraction
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/debugutil/pprof.go:30: undefined: runtime.SetMutexProfileFraction
```

**Comment by heyitsanthony** [comment]
@braddeicide is this with go1.8?

**Comment by braddeicide** [comment]
go version go1.7.3 linux/amd64

Is 1.8 required?

**Comment by heyitsanthony** [comment]
@braddeicide go 1.8 is needed to build master / 3.2, yes. The 3.1 branch will build with 1.7.

**Comment by braddeicide** [comment]
Yep, that's what i get for skimming :)

"For those wanting to try the very latest version, build etcd from the master branch. Go version 1.8+ is required to build the latest version of etcd"

Thanks.
