### ISSUE TITLE
etcd-2.2.0 build fails for arm64

### ISSUE THREAD

**Issue by glevand** [coreos/etcd#3623]
etcd-2.2.0 build fails for arm64 (go-1.5.1).

```
# github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt
../gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:85: undefined: maxMapSize
../gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:85: invalid array bound maxMapSize
```

**Comment by yichengq** [comment]
@mkaczanowski Could you confirm this is a problem?

**Comment by onlyjob** [comment]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803133
This problem also affects v2.2.1 on _arm64_, _ppc64el_ and _ppc64_.

**Comment by glevand** [comment]
I verified the arm64 build fails with v2.2.1.

**Comment by jonboulle** [comment]
@glevand have you tried building with `-tags arm64` ?

**Comment by gyuho** [comment]
Closing this. I tried to build with `amd64` with current 2.2 release branch https://github.com/coreos/etcd/tree/release-2.2 and it got built.

I used https://github.com/mitchellh/gox to build it.

Please ping us if it still fails.

**Comment by glevand** [comment]
Git bisect shows it was fixed in 4669b899cca9a326731a10e03c76605bf26470f6 (Godeps: update boltdb).

**Comment by bingli-ibm** [comment]
The boltdb in release branch may need to be updated.

s390x doesn't build with release-2.2.
Master builds fine.

I've figured out the root cause is boltdb. The bolddb version  in release-2.2 doesn't have bolt_s390x.go, but master has.

**Comment by glevand** [comment]
Commit https://github.com/coreos/etcd/commit/4669b899cca9a326731a10e03c76605bf26470f6 (Godeps: update boltdb) updated boltdb from v1.0-119-g90fef38 to v1.0-158-g81db894.

@gyuho can we get this into the next etcd release, either by merging https://github.com/coreos/etcd/commit/4669b899cca9a326731a10e03c76605bf26470f6, or branching from master after this commit?

**Comment by gyuho** [comment]
I will ask @xiang90 if we could cherry-pick it in next release.

**Comment by xiang90** [comment]
This is resolved in etcd 2.2.5 I believe.

**Comment by glevand** [comment]
Seems to be fixed.  Thanks.
